package com.mystic.blocksmelt;

import com.mystic.blocksmelt.recipe.AutogeneratedOreSmeltingRecipe;
import com.mojang.logging.LogUtils;
import net.minecraft.world.item.crafting.RecipeSerializer;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
import org.slf4j.Logger;

@Mod(Blocksmelt.MODID)
public class Blocksmelt {
    public static final String MODID = "blocksmelt";
    private static final Logger LOGGER = LogUtils.getLogger();
    public static final DeferredRegister<RecipeSerializer<?>> RECIPE_SERIALIZERS =
            DeferredRegister.create(ForgeRegistries.RECIPE_SERIALIZERS, MODID);
    public static final RegistryObject<RecipeSerializer<AutogeneratedOreSmeltingRecipe>>
            AUTOGENERATED_ORE_SMELTING_SERIALIZER = RECIPE_SERIALIZERS.register(
                    "autogenerated_ore_smelting",
                    AutogeneratedOreSmeltingRecipe.Serializer::new
            );

    public Blocksmelt() {
        IEventBus modEventBus = FMLJavaModLoadingContext.get().getModEventBus();
        RECIPE_SERIALIZERS.register(modEventBus);
        LOGGER.info("BlockSmelt loaded");
    }
}
